### ISSUE TITLE
Works on FORGE!! [documentation]

### ISSUE THREAD

**Issue by markygnlg** [Erb3/NoHotbarLooping#2]
FYI, not sure if this helps but I got nohotbarlooping-1.1.1-1.20.1_[FABRIC].jar to work on:
mc 1.20.1
forge 47.2.0 (& 47.1.3)

...by adding:
Sinytra Connector (Connector-1.0.0-beta.27+1.20.1.jar) - forge mod

& its requirement:
fabric-api-0.90.7+1.10.3+1.20.1.jar - forge mod

I am using around 4 fabric mods on forge loader because of this.
I love your mod so I thought it was worth sharing as I only learnt this a week ago.

**Comment by Erb3** [comment]
I'm really happy to hear that you like my mod, and thanks for sharing! I'll add something to the README.md about it 😺.
